import { Friend } from '../types/friend';

export const dummyFriends: Friend[] = [
  // 가족
  {
    id: '1',
    name: '김영수',
    tag: '가족',
    relation: '아빠',
    avatarColor: '#8B7560',
    initial: '영',
    isAppUser: true,
    sharedAlbumCount: 3,
    photoCount: 45,
  },
  {
    id: '2',
    name: '이미영',
    tag: '가족',
    relation: '엄마',
    avatarColor: '#C4919A',
    initial: '미',
    isAppUser: true,
    sharedAlbumCount: 3,
    photoCount: 62,
  },
  {
    id: '3',
    name: '김지수',
    tag: '가족',
    relation: '동생',
    avatarColor: '#92A888',
    initial: '지',
    isAppUser: true,
    sharedAlbumCount: 2,
    photoCount: 28,
  },

  // 연인
  {
    id: '4',
    name: '박서연',
    tag: '연인',
    relation: '애인',
    avatarColor: '#B8818A',
    initial: '서',
    isAppUser: true,
    sharedAlbumCount: 5,
    photoCount: 156,
  },

  // 친구
  {
    id: '5',
    name: '최민준',
    tag: '친구',
    memo: '대학 동기',
    avatarColor: '#7B8FA3',
    initial: '민',
    isAppUser: true,
    sharedAlbumCount: 2,
    photoCount: 34,
  },
  {
    id: '6',
    name: '정하은',
    tag: '친구',
    memo: '고등학교 친구',
    avatarColor: '#D4A855',
    initial: '하',
    isAppUser: false,
    sharedAlbumCount: 0,
    photoCount: 12,
  },
  {
    id: '7',
    name: '이도현',
    tag: '친구',
    memo: '동아리',
    avatarColor: '#859C78',
    initial: '도',
    isAppUser: true,
    sharedAlbumCount: 1,
    photoCount: 18,
  },
  {
    id: '8',
    name: '한소희',
    tag: '친구',
    memo: '같은 팀',
    avatarColor: '#A898B8',
    initial: '소',
    isAppUser: true,
    sharedAlbumCount: 1,
    photoCount: 22,
  },

  // 직장
  {
    id: '9',
    name: '윤재호',
    tag: '직장',
    memo: '팀장님',
    avatarColor: '#5B6E85',
    initial: '재',
    isAppUser: false,
    sharedAlbumCount: 0,
    photoCount: 5,
  },
  {
    id: '10',
    name: '송예진',
    tag: '직장',
    memo: '동기',
    avatarColor: '#D4A898',
    initial: '예',
    isAppUser: true,
    sharedAlbumCount: 1,
    photoCount: 15,
  },
];
